[package]
name = "patch-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mach2 = "0.4.2"
sysinfo = "0.31.2"
patch-core = {path = "../patch-core"}